
JVM fieldInsn: #GETSTATIC
    owner: 'java/lang/System'
    name: 'out'
    descr: 'Ljava/io/PrintStream;'.

JVM ldcInsn: 'Hello World'.

JVM methodInsn: #INVOKEVIRTUAL
    owner: 'java/io/PrintStream'
    name: 'print'
    descr: '(Ljava/lang/String;)V'
    iface: false.

JVM fieldInsn: #GETSTATIC
    owner: 'java/lang/System'
    name: 'out'
    descr: 'Ljava/io/PrintStream;'.

JVM methodInsn: #INVOKEVIRTUAL
    owner: 'java/io/PrintStream'
    name: 'println'
    descr: '()V'
    iface: false.
